#!/bin/zsh

tail -n +2 data/gamedata-saved.csv | cut -d, -f1 | while read -r gameid; do
  i=0

  gameid=`echo "$gameid" | tr -d '"'`
  echo "\n===============\n\nScrape gameid $gameid\n\n===============\n"
  casperjs scraping/reviews/scraper.js --gameid=$gameid &
  i=$(($i+1))

  if [[ i -gt 15 ]]; then
    wait
    i=0
  fi
done
